version: '3'
services:
  web:
    container_name: youtube-watchard-web
    build:
      context: ./web
    ports:
      - "3000:3000"
    depends_on:
      - server

  server:
    container_name: youtube-watchard-server
    build:
      context: ./server
    ports:
      - "5000:5000"